export const users = [
    {
        documentType: "Tarjeta de identidad",
        numberDocument: "1234567890",
        firstName: "John",
        middleName: "MiddleName1",
        lastNames: "Doe",
        bornDate: "1990-01-01",
        gender: "Masculino",
        email: "john.doe@example.com",
        phone: "1234567890",
        picture: "user1.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
    {
        documentType: "Cédula",
        numberDocument: "0987654321",
        firstName: "Jane",
        middleName: "MiddleName2",
        lastNames: "Smith",
        bornDate: "1995-05-15",
        gender: "Femenino",
        email: "jane.smith@example.com",
        phone: "9876543210",
        picture: "user2.jpg",
    },
];

console.log(users);
